name: Auto Increment Version and Create Tag

on:
  push:
    branches:
      - main

jobs:
  auto_increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'rajr1610'
          git config --global user.email 'r.ramanathan@netxd.com'

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Increment version
        id: increment_version
        run: |
          current_tag=${{ steps.latest_tag.outputs.tag }}
          IFS='.' read -r -a version_parts <<< "$current_tag"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}

          new_patch=$((patch + 1))
          new_tag="V.${major}.${minor}.${new_patch}_QA"
          echo "::set-output name=new_tag::$new_tag"

      - name: Commit version increment
        run: |
          git tag ${{ steps.increment_version.outputs.new_tag }}
          git push origin ${{ steps.increment_version.outputs.new_tag }}

